/* generated by rust_qt_binding_generator */
#include "test_tree_rust.h"

namespace {
    template <typename T>
    struct option {
    private:
        T value;
        bool some;
    public:
        operator QVariant() const {
            if (some) {
                return QVariant(value);
            }
            return QVariant();
        }
    };
    struct qbytearray_t {
    private:
        const char* data;
        int len;
    public:
        qbytearray_t(const QByteArray& v):
            data(v.data()),
            len(v.size()) {
        }
        operator QByteArray() const {
            return QByteArray(data, len);
        }
    };
    struct qstring_t {
    private:
        const void* data;
        int len;
    public:
        qstring_t(const QString& v):
            data(static_cast<const void*>(v.utf16())),
            len(v.size()) {
        }
        operator QString() const {
            return QString::fromUtf8(static_cast<const char*>(data), len);
        }
    };
    struct qmodelindex_t {
        int row;
        quintptr id;
    };
}
typedef void (*qstring_set)(QString*, qstring_t*);
void set_qstring(QString* v, qstring_t* val) {
    *v = *val;
}
typedef void (*qbytearray_set)(QByteArray*, qbytearray_t*);
void set_qbytearray(QByteArray* v, qbytearray_t* val) {
    *v = *val;
}

extern "C" {
    void persons_data_user_name(const Persons::Private*, int, quintptr, QString*, qstring_set);
    bool persons_set_data_user_name(Persons::Private*, int, quintptr, qstring_t);
    void persons_sort(Persons::Private*, unsigned char column, Qt::SortOrder order = Qt::AscendingOrder);

    int persons_row_count(const Persons::Private*, int, quintptr);
    bool persons_can_fetch_more(const Persons::Private*, int, quintptr);
    void persons_fetch_more(Persons::Private*, int, quintptr);
    quintptr persons_index(const Persons::Private*, int, quintptr);
    qmodelindex_t persons_parent(const Persons::Private*, quintptr);
}
int Persons::columnCount(const QModelIndex &) const
{
    return 1;
}

bool Persons::hasChildren(const QModelIndex &parent) const
{
    return rowCount(parent) > 0;
}

int Persons::rowCount(const QModelIndex &parent) const
{
    if (parent.isValid() && parent.column() != 0) {
        return 0;
    }
    return persons_row_count(d, parent.row(), parent.internalId());
}

QModelIndex Persons::index(int row, int column, const QModelIndex &parent) const
{
    if (row < 0 || column < 0 || column >= 1) {
        return QModelIndex();
    }
    if (parent.isValid() && parent.column() != 0) {
        return QModelIndex();
    }
    const quintptr id = persons_index(d, parent.row(), parent.internalId());
    return createIndex(row, column, id);
}

QModelIndex Persons::parent(const QModelIndex &index) const
{
    if (!index.isValid()) {
        return QModelIndex();
    }
    const qmodelindex_t parent = persons_parent(d, index.internalId());
    return parent.row >= 0 ?createIndex(parent.row, 0, parent.id) :QModelIndex();
}

bool Persons::canFetchMore(const QModelIndex &parent) const
{
    if (parent.isValid() && parent.column() != 0) {
        return false;
    }
    return persons_can_fetch_more(d, parent.row(), parent.internalId());
}

void Persons::fetchMore(const QModelIndex &parent)
{
    persons_fetch_more(d, parent.row(), parent.internalId());
}

void Persons::sort(int column, Qt::SortOrder order)
{
    persons_sort(d, column, order);
}
Qt::ItemFlags Persons::flags(const QModelIndex &i) const
{
    auto flags = QAbstractItemModel::flags(i);
    if (i.column() == 0) {
        flags |= Qt::ItemIsEditable;
    }
    return flags;
}
QVariant Persons::data(const QModelIndex &index, int role) const
{
    QVariant v;
    QString s;
    QByteArray b;
    switch (index.column()) {
    case 0:
        switch (role) {
        case Qt::DisplayRole:
        case Qt::EditRole:
        case Qt::UserRole + 0:
            persons_data_user_name(d, index.row(), index.internalId(), &s, set_qstring);
            if (!s.isNull()) v.setValue<QString>(s);
            break;
        }
        break;
    }
    return v;
}
QHash<int, QByteArray> Persons::roleNames() const {
    QHash<int, QByteArray> names = QAbstractItemModel::roleNames();
    names.insert(Qt::UserRole + 0, "userName");
    return names;
}
bool Persons::setData(const QModelIndex &index, const QVariant &value, int role)
{
    bool set = false;
    if (index.column() == 0) {
        if (role == Qt::DisplayRole || role == Qt::EditRole || role == Qt::UserRole + 0) {
            set = persons_set_data_user_name(d, index.row(), index.internalId(), value.value<QString>());
        }
    }
    if (set) {
        emit dataChanged(index, index, QVector<int>() << role);
    }
    return set;
}
extern "C" {
    Persons::Private* persons_new(Persons*,
        void (*)(const Persons*, quintptr),
        void (*)(Persons*),
        void (*)(Persons*),
        void (*)(Persons*, quintptr, int, int),
        void (*)(Persons*),
        void (*)(Persons*, quintptr, int, int),
        void (*)(Persons*));
    void persons_free(Persons::Private*);
};
Persons::Persons(QObject *parent):
    QAbstractItemModel(parent),
    d(persons_new(this,
        [](const Persons* o, quintptr id) {
            auto i = persons_parent(o->d, id);
            emit o->newDataReady(o->createIndex(i.row, 0, i.id));
        },
        [](Persons* o) {
            o->beginResetModel();
        },
        [](Persons* o) {
            o->endResetModel();
        },
        [](Persons* o, quintptr id, int first, int last) {
                       auto i = persons_parent(o->d, id);
            o->beginInsertRows(o->createIndex(i.row, 0, i.id), first, last);
        },
        [](Persons* o) {
            o->endInsertRows();
        },
        [](Persons* o, quintptr id, int first, int last) {
                       auto i = persons_parent(o->d, id);
            o->beginRemoveRows(o->createIndex(i.row, 0, i.id), first, last);
        },
        [](Persons* o) {
            o->endRemoveRows();
        }
    )) {
    connect(this, &Persons::newDataReady, this, [this](const QModelIndex& i) {
        fetchMore(i);
    }, Qt::QueuedConnection);
}


Persons::~Persons() {
    persons_free(d);
}
