/* generated by rust_qt_binding_generator */
#ifndef TEST_OBJECT_TYPES_RUST_H
#define TEST_OBJECT_TYPES_RUST_H

#include <QObject>
#include <QVariant>
#include <QAbstractItemModel>

class PersonInterface;
class Person : public QObject
{
    Q_OBJECT
    PersonInterface * const d;
    Q_PROPERTY(QVariant userName READ userName WRITE setUserName NOTIFY userNameChanged FINAL)
public:
    explicit Person(QObject *parent = nullptr);
    ~Person();
    QVariant userName() const;
    void setUserName(const QVariant& v);
signals:
    void userNameChanged();
private:
    QVariant m_userName;
};
#endif // TEST_OBJECT_TYPES_RUST_H
