/* generated by rust_qt_binding_generator */
#ifndef TEST_OBJECT_RUST_H
#define TEST_OBJECT_RUST_H

#include <QObject>
#include <QAbstractItemModel>

class Person;

class Person : public QObject
{
    Q_OBJECT
public:
    class Private;
private:
    Private * m_d;
    bool m_ownsPrivate;
    Q_PROPERTY(QString userName READ userName WRITE setUserName NOTIFY userNameChanged FINAL)
    explicit Person(bool owned, QObject *parent);
public:
    explicit Person(QObject *parent = nullptr);
    ~Person();
    QString userName() const;
    void setUserName(const QString& v);
Q_SIGNALS:
    void userNameChanged();
};
#endif // TEST_OBJECT_RUST_H
