/* generated by rust_qt_binding_generator */
#ifndef TEST_OBJECT_RUST_H
#define TEST_OBJECT_RUST_H

#include <QObject>
#include <QAbstractItemModel>

class Person : public QObject
{
    Q_OBJECT
public:
    class Private;
private:
    Private * const d;
    Q_PROPERTY(QString userName READ userName WRITE setUserName NOTIFY userNameChanged FINAL)
public:
    explicit Person(QObject *parent = nullptr);
    ~Person();
    QString userName() const;
    void setUserName(const QString& v);
signals:
    void userNameChanged();
private:
    QString m_userName;
};
#endif // TEST_OBJECT_RUST_H
