/* generated by rust_qt_binding_generator */
#ifndef TREE_H
#define TREE_H

#include <QObject>
#include <QAbstractItemModel>

class TreeInterface;
class Tree : public QAbstractItemModel
{
    Q_OBJECT
    TreeInterface * const d;
    Q_PROPERTY(QString path READ path WRITE setPath NOTIFY pathChanged FINAL)
public:
    explicit Tree(QObject *parent = nullptr);
    ~Tree();
    QString path() const;
    void setPath(const QString& v);

    int columnCount(const QModelIndex &parent = QModelIndex()) const;
    QVariant data(const QModelIndex &index, int role = Qt::DisplayRole) const;
    QModelIndex index(int row, int column, const QModelIndex &parent = QModelIndex()) const;
    QModelIndex parent(const QModelIndex &index) const;
    int rowCount(const QModelIndex &parent = QModelIndex()) const;
    bool canFetchMore(const QModelIndex &parent) const;
    void fetchMore(const QModelIndex &parent);
    QHash<int, QByteArray> roleNames() const;
signals:
    void newDataReady();
signals:
    void pathChanged();
private:
    QString m_path;
};
#endif // TREE_H
